// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using PMS.Data;
using System;

namespace PMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171104054037_UpdateInfoUser")]
    partial class UpdateInfoUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PMS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Avatar");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Major");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("PMS.Models.Council", b =>
                {
                    b.Property<int>("CouncilId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ResultGrade");

                    b.Property<string>("ResultScore");

                    b.HasKey("CouncilId");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasFilter("[GroupId] IS NOT NULL");

                    b.ToTable("Council");
                });

            modelBuilder.Entity("PMS.Models.CouncilEnrollment", b =>
                {
                    b.Property<int>("CouncilEnrollmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CouncilId");

                    b.Property<int?>("CouncilRoleId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LecturerId");

                    b.Property<double?>("Percentage");

                    b.Property<bool>("isMark");

                    b.HasKey("CouncilEnrollmentId");

                    b.HasIndex("CouncilId");

                    b.HasIndex("CouncilRoleId");

                    b.HasIndex("LecturerId");

                    b.ToTable("CouncilErollment");
                });

            modelBuilder.Entity("PMS.Models.CouncilRole", b =>
                {
                    b.Property<int>("CouncilRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CouncilRoleName");

                    b.HasKey("CouncilRoleId");

                    b.ToTable("CouncilRole");
                });

            modelBuilder.Entity("PMS.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<int?>("GradeId");

                    b.Property<int?>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("QuarterId");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("StudentId");

                    b.Property<string>("Type");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("GradeId")
                        .IsUnique()
                        .HasFilter("[GradeId] IS NOT NULL");

                    b.HasIndex("GroupId");

                    b.HasIndex("QuarterId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("PMS.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GradeType");

                    b.Property<string>("IsDeleted");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("PMS.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName");

                    b.Property<int?>("LecturerId");

                    b.Property<int?>("MajorId");

                    b.Property<int?>("ProjectId");

                    b.Property<int?>("QuarterId");

                    b.Property<string>("isConfirm");

                    b.Property<bool>("isDeleted");

                    b.HasKey("GroupId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("MajorId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QuarterId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("PMS.Models.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("MajorId");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("LecturerId");

                    b.HasIndex("MajorId");

                    b.ToTable("Lecturer");
                });

            modelBuilder.Entity("PMS.Models.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MajorCode");

                    b.Property<string>("MajorName");

                    b.HasKey("MajorId");

                    b.ToTable("Major");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LecturerId");

                    b.Property<int?>("MajorId");

                    b.Property<string>("ProjectCode");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("ProjectId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("MajorId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("PMS.Models.Quarter", b =>
                {
                    b.Property<int>("QuarterId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("QuarterEnd");

                    b.Property<string>("QuarterName");

                    b.Property<DateTime>("QuarterStart");

                    b.HasKey("QuarterId");

                    b.ToTable("Quarter");
                });

            modelBuilder.Entity("PMS.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("MajorId");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("StudentCode");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("PMS.Models.UploadedFile", b =>
                {
                    b.Property<int>("UploadedFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("EnrollmentId");

                    b.Property<int?>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("UploadedFileId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("GroupId");

                    b.ToTable("UploadedFile");
                });

            modelBuilder.Entity("PMS.Models.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<DateTime>("UpdatedOn");

                    b.ToTable("ApplicationRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PMS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PMS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PMS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PMS.Models.Council", b =>
                {
                    b.HasOne("PMS.Models.Group", "Group")
                        .WithOne("Council")
                        .HasForeignKey("PMS.Models.Council", "GroupId");
                });

            modelBuilder.Entity("PMS.Models.CouncilEnrollment", b =>
                {
                    b.HasOne("PMS.Models.Council", "Council")
                        .WithMany("CouncilEnrollments")
                        .HasForeignKey("CouncilId");

                    b.HasOne("PMS.Models.CouncilRole", "CouncilRole")
                        .WithMany()
                        .HasForeignKey("CouncilRoleId");

                    b.HasOne("PMS.Models.Lecturer", "Lecturer")
                        .WithMany("CouncilEnrollments")
                        .HasForeignKey("LecturerId");
                });

            modelBuilder.Entity("PMS.Models.Enrollment", b =>
                {
                    b.HasOne("PMS.Models.Grade", "Grade")
                        .WithOne("Enrollment")
                        .HasForeignKey("PMS.Models.Enrollment", "GradeId");

                    b.HasOne("PMS.Models.Group", "Group")
                        .WithMany("Enrollments")
                        .HasForeignKey("GroupId");

                    b.HasOne("PMS.Models.Quarter", "Quarter")
                        .WithMany("Enrollments")
                        .HasForeignKey("QuarterId");

                    b.HasOne("PMS.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("PMS.Models.Group", b =>
                {
                    b.HasOne("PMS.Models.Lecturer", "Lecturer")
                        .WithMany("Groups")
                        .HasForeignKey("LecturerId");

                    b.HasOne("PMS.Models.Major", "Major")
                        .WithMany("Groups")
                        .HasForeignKey("MajorId");

                    b.HasOne("PMS.Models.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId");

                    b.HasOne("PMS.Models.Quarter", "Quarter")
                        .WithMany("Groups")
                        .HasForeignKey("QuarterId");
                });

            modelBuilder.Entity("PMS.Models.Lecturer", b =>
                {
                    b.HasOne("PMS.Models.Major", "Major")
                        .WithMany("Lecturers")
                        .HasForeignKey("MajorId");
                });

            modelBuilder.Entity("PMS.Models.Project", b =>
                {
                    b.HasOne("PMS.Models.Lecturer", "Lecturer")
                        .WithMany("projectRepository")
                        .HasForeignKey("LecturerId");

                    b.HasOne("PMS.Models.Major", "Major")
                        .WithMany("Projects")
                        .HasForeignKey("MajorId");
                });

            modelBuilder.Entity("PMS.Models.Student", b =>
                {
                    b.HasOne("PMS.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId");
                });

            modelBuilder.Entity("PMS.Models.UploadedFile", b =>
                {
                    b.HasOne("PMS.Models.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMS.Models.Group")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
